name = "jmm-backend"
main = "src/index.ts"
compatibility_date = "2026-04-10"
workers_dev = true

[vars]
CORS_ORIGIN = "https://app.jechangemamutuelle.online"

[[d1_databases]]
binding = "DB"
database_name = "jmm-prod-db"
database_id = "74e351d5-ebf4-4a3f-8c2e-d3e4c9700d82"

# Optional observability
[observability]
enabled = true
